window.TOOLBOX_DATA = {
  summary: [
    "左侧固定分类导航",
    "顶部搜索与统计",
    "推荐工具区",
    "按分类卡片列表",
    "收藏与主题切换",
    "工具即开即用",
  ],
  categories: [
    { id: "featured", name: "推荐工具", icon: "HOT", description: "高频使用、打开即用的入口。" },
    { id: "living", name: "生活工具", icon: "LIF", description: "时间管理、日常记录与生活计算。" },
    { id: "security", name: "加密解密", icon: "SEC", description: "摘要、编码与常用安全处理。" },
    { id: "coding", name: "编码转码", icon: "COD", description: "Base64、URL、时间戳等常见转换。" },
    { id: "format", name: "格式工具", icon: "FMT", description: "JSON、文本与结构化内容整理。" },
    { id: "webmaster", name: "站长工具", icon: "WEB", description: "网络、页面与基础参数计算。" },
    { id: "image", name: "图片颜色", icon: "CLR", description: "颜色值、对比度与取色换算。" },
    { id: "text", name: "文本工具", icon: "TXT", description: "文本统计、大小写和批量清洗。" },
    { id: "math", name: "数学工具", icon: "MAT", description: "计算器、换算器和理财计算。" },
    { id: "creation", name: "生成工具", icon: "GEN", description: "密码、随机项和内容生成。" },
    { id: "pdf", name: "PDF工具", icon: "PDF", description: "保留入口，方便后续继续扩展。" },
    { id: "utility", name: "实用工具", icon: "USE", description: "计时、记事、计分和设备辅助。" },
    { id: "health", name: "健康养生", icon: "HLT", description: "BMI、饮水、热量和健康参考。" },
    { id: "fun", name: "娱乐工具", icon: "FUN", description: "随机娱乐、反应测试和小游戏。" },
  ],
  featuredToolIds: [
    "pomodoro",
    "calculator",
    "password-generator",
    "countdown",
    "json-formatter",
    "meal-picker",
  ],
  tools: [
    {
      id: "calculator",
      title: "在线计算器",
      description: "支持四则运算和百分比的便捷计算器。",
      category: "featured",
      tags: ["数学", "办公"],
      tool: "calculator",
      implemented: true,
    },
    {
      id: "pomodoro",
      title: "番茄时钟",
      description: "可自定义工作与休息时长的专注计时工具。",
      category: "featured",
      tags: ["专注", "时间"],
      tool: "pomodoro",
      implemented: true,
    },
    {
      id: "password-generator",
      title: "随机密码生成器",
      description: "生成含数字、大小写和符号的安全密码。",
      category: "featured",
      tags: ["密码", "生成"],
      tool: "password",
      implemented: true,
    },
    {
      id: "countdown",
      title: "在线倒计时器",
      description: "输入目标时间后即时显示剩余天数与秒数。",
      category: "featured",
      tags: ["倒计时", "计划"],
      tool: "countdown",
      implemented: true,
    },
    {
      id: "bmi",
      title: "BMI 标准身高体重计算",
      description: "计算 BMI 指数并判断体重区间。",
      category: "featured",
      tags: ["健康", "体重"],
      tool: "bmi",
      implemented: true,
    },
    {
      id: "meal-picker",
      title: "今天吃什么",
      description: "给犹豫不决的时候来一次随机决策。",
      category: "featured",
      tags: ["娱乐", "生活"],
      tool: "mealPicker",
      implemented: true,
    },
    {
      id: "stopwatch",
      title: "秒表计时工具",
      description: "支持开始、暂停、复位和分段记录。",
      category: "living",
      tags: ["计时", "效率"],
      tool: "stopwatch",
      implemented: true,
    },
    {
      id: "age-calculator",
      title: "年龄计算器",
      description: "根据出生日期计算年龄、月份和总天数。",
      category: "living",
      tags: ["日期", "生日"],
      tool: "ageCalculator",
      implemented: true,
    },
    {
      id: "date-diff",
      title: "日期差计算器",
      description: "计算两个日期之间相差多少天和周。",
      category: "living",
      tags: ["日期", "计划"],
      tool: "dateDiff",
      implemented: true,
    },
    {
      id: "salary-converter",
      title: "单双休薪资换算",
      description: "把月薪拆解为日薪、时薪，便于横向比较。",
      category: "living",
      tags: ["工资", "职场"],
      tool: "salaryConverter",
      implemented: true,
    },
    {
      id: "alarm-board",
      title: "在线记事板",
      description: "基于本地存储的临时笔记本，刷新后仍保留。",
      category: "living",
      tags: ["记录", "便签"],
      tool: "notepad",
      implemented: true,
    },
    {
      id: "holiday-plan",
      title: "假期倒排规划",
      description: "为节假日、考试、出差设置目标日期并查看节奏。",
      category: "living",
      tags: ["日历", "安排"],
      tool: "countdown",
      implemented: true,
    },
    {
      id: "sha-generator",
      title: "SHA 摘要工具",
      description: "支持 SHA-1 / SHA-256 / SHA-384 / SHA-512 摘要。",
      category: "security",
      tags: ["摘要", "安全"],
      tool: "shaGenerator",
      implemented: true,
    },
    {
      id: "base64-tool",
      title: "Base64 编码解码",
      description: "在文本和 Base64 之间快速互转。",
      category: "security",
      tags: ["加密", "编码"],
      tool: "base64Tool",
      implemented: true,
    },
    {
      id: "url-tool",
      title: "URL 编码解码",
      description: "用于参数转义和调试链接内容。",
      category: "security",
      tags: ["URL", "转义"],
      tool: "urlTool",
      implemented: true,
    },
    {
      id: "password-checker",
      title: "密码强度评估",
      description: "分析长度、字符类型和基础强度表现。",
      category: "security",
      tags: ["密码", "检测"],
      tool: "passwordStrength",
      implemented: true,
    },
    {
      id: "timestamp-tool",
      title: "时间戳转换",
      description: "时间戳与常规日期时间之间双向转换。",
      category: "coding",
      tags: ["时间戳", "开发"],
      tool: "timestampTool",
      implemented: true,
    },
    {
      id: "unicode-tool",
      title: "Unicode 转换",
      description: "查看字符串的 Unicode 编码点信息。",
      category: "coding",
      tags: ["Unicode", "开发"],
      tool: "unicodeTool",
      implemented: true,
    },
    {
      id: "json-formatter",
      title: "JSON 格式化",
      description: "校验、压缩和美化 JSON 内容。",
      category: "format",
      tags: ["JSON", "格式化"],
      tool: "jsonFormatter",
      implemented: true,
    },
    {
      id: "text-cleaner",
      title: "文本清洗",
      description: "批量去空行、去首尾空格和重复行。",
      category: "format",
      tags: ["文本", "整理"],
      tool: "textCleaner",
      implemented: true,
    },
    {
      id: "text-counter",
      title: "字数统计",
      description: "统计字数、词数、行数和段落数量。",
      category: "text",
      tags: ["统计", "写作"],
      tool: "textCounter",
      implemented: true,
    },
    {
      id: "case-converter",
      title: "大小写转换",
      description: "支持全大写、全小写、标题格式和句首大写。",
      category: "text",
      tags: ["大小写", "文本"],
      tool: "caseConverter",
      implemented: true,
    },
    {
      id: "random-picker",
      title: "随机点名工具",
      description: "输入多行名单，一键随机抽取结果。",
      category: "text",
      tags: ["随机", "课堂"],
      tool: "randomPicker",
      implemented: true,
    },
    {
      id: "regex-helper",
      title: "正则辅助说明",
      description: "提供简单的正则测试入口和结果展示。",
      category: "text",
      tags: ["Regex", "开发"],
      tool: "regexTester",
      implemented: true,
    },
    {
      id: "loan-calculator",
      title: "贷款月供计算器",
      description: "根据本金、年化利率和年限估算月供。",
      category: "math",
      tags: ["理财", "月供"],
      tool: "loanCalculator",
      implemented: true,
    },
    {
      id: "unit-converter",
      title: "单位换算器",
      description: "支持长度、重量、温度三类常用换算。",
      category: "math",
      tags: ["换算", "日常"],
      tool: "unitConverter",
      implemented: true,
    },
    {
      id: "tip-calculator",
      title: "消费分摊计算器",
      description: "计算小费、总价和多人分摊金额。",
      category: "math",
      tags: ["分摊", "聚餐"],
      tool: "tipCalculator",
      implemented: true,
    },
    {
      id: "water-intake",
      title: "每日饮水计算器",
      description: "根据体重和活动量估算推荐饮水量。",
      category: "health",
      tags: ["饮水", "健康"],
      tool: "waterIntake",
      implemented: true,
    },
    {
      id: "bmr-calculator",
      title: "基础代谢率 BMR",
      description: "按性别、身高、体重和年龄估算基础代谢。",
      category: "health",
      tags: ["代谢", "健身"],
      tool: "bmrCalculator",
      implemented: true,
    },
    {
      id: "pace-calculator",
      title: "配速计算器",
      description: "输入距离和总用时，反推出每公里配速。",
      category: "health",
      tags: ["跑步", "配速"],
      tool: "paceCalculator",
      implemented: true,
    },
    {
      id: "color-converter",
      title: "HEX / RGB 转换",
      description: "快速在十六进制与 RGB 颜色值之间切换。",
      category: "image",
      tags: ["颜色", "设计"],
      tool: "colorConverter",
      implemented: true,
    },
    {
      id: "contrast-checker",
      title: "颜色对比度检查",
      description: "检查前景色与背景色的对比度等级。",
      category: "image",
      tags: ["可访问性", "UI"],
      tool: "contrastChecker",
      implemented: true,
    },
    {
      id: "screen-cleaner",
      title: "扬声器清灰音",
      description: "生成高频测试音，用于设备清灰演示。",
      category: "utility",
      tags: ["设备", "音频"],
      tool: "speakerCleaner",
      implemented: true,
    },
    {
      id: "score-board",
      title: "在线记分板",
      description: "支持两队比分增减和快速复位。",
      category: "utility",
      tags: ["比赛", "互动"],
      tool: "scoreBoard",
      implemented: true,
    },
    {
      id: "reaction-test",
      title: "反应速度测试",
      description: "点击开始后测试你的视觉反应速度。",
      category: "fun",
      tags: ["测试", "小游戏"],
      tool: "reactionTest",
      implemented: true,
    },
    {
      id: "coin-dice",
      title: "抛硬币与骰子",
      description: "适合做快速选择或小游戏随机数。",
      category: "fun",
      tags: ["随机", "娱乐"],
      tool: "coinDice",
      implemented: true,
    },
    {
      id: "answer-book",
      title: "答案之书",
      description: "给纠结时刻一个轻松的随机回答。",
      category: "fun",
      tags: ["随机", "治愈"],
      tool: "answerBook",
      implemented: true,
    },
    {
      id: "pdf-workbench",
      title: "PDF 工具台",
      description: "保留为扩展位，可继续接入拆分、合并与压缩。",
      category: "pdf",
      tags: ["PDF", "扩展"],
      implemented: false,
    },
    {
      id: "ip-helper",
      title: "网络参数工具",
      description: "预留站长工具区域，方便后续接入 IP/UA 查询。",
      category: "webmaster",
      tags: ["网络", "扩展"],
      implemented: false,
    },
    {
      id: "mind-board",
      title: "在线白板",
      description: "当前版本保留入口，后续可升级为画布功能。",
      category: "creation",
      tags: ["白板", "协作"],
      implemented: false,
    },
  ],
};
